/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package TraPOO;

import TraPOO.Jogador.Atacante;
import TraPOO.Jogador.Goleiro;
import TraPOO.Time.Time;

public class App {
    public static void main(String[] args) {
        Goleiro g1 = new Goleiro(181, 89,"Bruno", "2000-06-29", 0);
        Atacante a1 = new Atacante(40, 80, "Romario", "1976-07-11", 10);
        Time azul = new Time("Azul");
        
        System.out.println("Nome: " + g1.getNome());
        System.out.println("Idade: " + g1.getIdade());
        System.out.println("Habilidade: " + g1.getHabilidade());
        System.out.println("Camisa: " + g1.getCamisa());
        System.out.println("Funcao: " + g1.getFuncao());
        
        System.out.println("\nNome: " + a1.getNome());
        System.out.println("Idade: " + a1.getIdade());
        System.out.println("Habilidade: " + a1.getHabilidade());
        System.out.println("Camisa: " + a1.getCamisa());
        System.out.println("Funcao: " + a1.getFuncao());
        
        azul.setJogador(g1);
        azul.setJogador(a1);
        System.out.println("\n" + azul.getJogadores());
        System.out.println("Habilidade Time: " + azul.totalHabilidade());
        
    }
}
